# Site settings
title: 默言，在路上
email: rugang6891@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://makeiteasy.github.com" # the base hostname & protocol for your site
url: 
# twitter_username: ""
github_username:  makeiteasy
rss_path: "feed.xml"

# Build settings
markdown: kramdown

author:
  bio: David 默言
  github: makeiteasy
  email_md5: 20dd8002c39f3b564675914c9858a2cd
  email: rugang6891@gmail.com
