# Site settings
title: To Be Continue
email: rugang6891@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  David, To Be Continue. 这里是David的个人博客。
  一个80后程序员的技术小窝。喜欢技术，热爱生活...
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://makeiteasy.github.com" # the base hostname & protocol for your site
url: 
# twitter_username: ""
github_username:  makeiteasy
rss_path: "feed.xml"

# Output settings
permalink: /:year/:month/:day/:title.html

# Build settings
# markdown: kramdown
markdown: redcarpet
# extensions: [fenced_code_blocks]

author:
  name: 代如刚
  bio: David 默言
  github: makeiteasy
  email_md5: 20dd8002c39f3b564675914c9858a2cd
  email: rugang6891@gmail.com

# 分页
paginate: 10
